name: Lambda Ecom Test Report
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "00 20 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run tests
        run: mvn clean test -Denv=suite

      - name: Git allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          allure_report: allure-report

      - name: Publish test report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Create and upload logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Logs
          path: logs/
